apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials-secret
  namespace: entebus
stringData:
  # Override this value in each overlay
  CLOUDFLARE_TUNNEL_TOKEN: "eyJhIjoiNjFiZjc5MjgzMmVjZjk0MzgzNDRmOTNlOWI3YzEzYjUiLCJ0IjoiMmY3MmU2MmEtYzAyNi00MTEyLThjYjEtMGFkZDU1OWZlNGIwIiwicyI6Ik1qTm1OVEkzWXpFdFpEQmpNUzAwT0dVMkxUaG1PRE10WWpBNVltSTFaVE16WldNNCJ9"
