apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: entebus
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      serviceAccountName: cloudflared
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CLOUDFLARE_TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-credentials-secret
                  key: CLOUDFLARE_TUNNEL_TOKEN
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(CLOUDFLARE_TUNNEL_TOKEN)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: entebus
