apiVersion: v1
kind: Secret
metadata:
  name: entebus-server-secret
  namespace: entebus
stringData:
  # Override these values in each overlay
  PSQL_DB_USERNAME: "postgres"
  PSQL_DB_PASSWORD: "change-me"
  REDIS_PASSWORD: "change-me"
  MINIO_ROOT_USER: "minio"
  MINIO_ROOT_PASSWORD: "change-me"
  OPENOBSERVE_USERNAME: "contact@entebus.com"
  OPENOBSERVE_PASSWORD: "change-me"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: entebus-server-config
  namespace: entebus
data:
  # PostgreSQL
  PSQL_DB_DRIVER: "postgresql"
  PSQL_DB_HOST: "postgis"
  PSQL_DB_PORT: "5432"
  PSQL_DB_NAME: "postgis"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # MinIO
  MINIO_HOST: "minio"
  MINIO_PORT: "9000"

  # OpenObserve
  OPENOBSERVE_HOST: "openobserve"
  OPENOBSERVE_PORT: "5080"
